name: Deploy Automatizado

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build da imagem Docker
        run: docker build -t ellen25/backend ./backend

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push da imagem para o Docker Hub
        run: docker push ellen25/backend

      # Deploy da aplicação no servidor remoto
      - name: Deploy da aplicação no servidor remoto
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop backend || true
            docker rm backend || true
            docker pull ellen25/backend
            docker run -d --name backend -p 8261:3000 ellen25/backend

      # Start SonarQube container no servidor remoto
      - name: Start SonarQube container no servidor remoto
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run -d --name sonar -p 8263:9000 sonarqube
            sleep 40

      # Rodar análise SonarQube via scanner em container no servidor remoto
      - name: Rodar análise SonarQube via scanner
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          script: |
            docker run --rm \
              -e SONAR_HOST_URL="http://localhost:8263" \
              -e SONAR_LOGIN="${SONAR_TOKEN}" \
              -v /home/aluno/backend:/usr/src \
              sonarsource/sonar-scanner-cli \
              -Dsonar.projectKey=backend \
              -Dsonar.sources=.

      # Parar e remover container SonarQube após análise
      - name: Parar e remover container SonarQube
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop sonar
            docker rm sonar
